name: homework3

on:
  workflow_dispatch: 

env:
  ENV: dev

jobs:
  homework: 
    runs-on: ubuntu-latest
      steps: 
        - name: output
          run: |
            echo "Runnig in $ENV environment"
            echo "API_KEY is ${{ secrets.API_KEY}}"
          
  
