name: homework6

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: File create
        run: echo "version=1.0.${{github.run_number}}" >version.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: version-upload
          path: version.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: action/download-artifact@v4
        with:
          name: version-upload
      - name: Cat file
        run: cat version.txt
