name: Step1 CI

on: 
  push:
    branches: ["main"]

jobs:
  homework:
    runs-on: ubuntu-latest
    steps: 
      - name: MyName
        run: echo "My Name is jay"      
      - name: Today
        run: echo "Today is CI Practice"
