name: TF Apply (Prod)

on: 
  workflow_dispatch:
    inputs:
      workpath:
        type: choice
        description: "Select target directory"
        options:
          - bootstrap
          - infra/terraform/root
        required: true
        default: infra/terraform/root
      action: 
        type: choice
        description: "plan or apply"
        options: [plan, apply]
        required: true
        default: plan

permissions: 
  id-token: write
  contents: read

concurrency: 
  group: tf-prod-${{inputs.workpath}}
  cancel-in-progress: false

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: prod
    env: 
      ARM_USE_OIDC: "true"
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    defaults:
      run:
        working-directory: ${{inputs.workpath}}

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          set -euo pipefail
          terraform init -input=false

      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: |
          set -euo pipefail
          terraform plan 

      - name: Terraform Apply (From Saved Plan)
        if: inputs.action == 'apply'
        run: |
          set -euo pipefail
          terraform apply -auto-approve